title: Dr. Assemgul Kozhabek
logo: docs/assets/FSPA0183.JPG
description: Hi, welcome to my website! ğŸŒ I am a curious researcher ğŸ” and a data scientist ğŸ’». I have expertise and experience with urban traffic data set analysis ğŸš—ğŸ“Š.
theme: jekyll-theme-minimal
