title: Dr. Assemgul Kozhabek
logo: docs/assets/FSPA0183.JPG
description: Researcher, Data Scientist. Hi, welcome to my website! ğŸŒŸ I am an intellectually curious researcher ğŸ” with a multidisciplinary mindset ğŸ§ . I have expertise and experience with urban traffic data set analysis ğŸš—ğŸ“Š.
theme: jekyll-theme-minimal
